/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DeveloperPortalTest;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
//import org.openqa.selenium.chrome.ChromeDriver;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws InterruptedException {
        
        System.setProperty("webdriver.gecko.driver", "/Users/stevendearborn/workspace/developerportaltest/geckodriver");

        //System.setProperty("webdriver.firefox.marionette", "/Users/stevendearborn/workspace/developerportaltest/geckodriver");
        
        //System.setProperty("webdriver.chrome.driver","chromedriver");
        //System.out.println(new App().getGreeting());
        
        //WebDriver driver = new ChromeDriver();
        FirefoxOptions options = new FirefoxOptions();

        WebDriver driver = new FirefoxDriver(options);
        try {
        driver.get("https://developer.usps.com");
        
        String title = driver.getTitle();
        
        System.out.print(title);
        
        WebElement apidoc = driver.findElement(By.linkText("API Catalog"));
        
        apidoc.click();
        
        //WebElement api = driver.findElement(By.className("card-title"));
        
        //System.out.print(api.getAccessibleName());
        
        //api.click();
        APICatalogPage APIs = new APICatalogPage(driver);
        
        //driver.findElement(By.linkText("Addresses")).click();
        }
        finally {
            //driver.close();
            driver.quit();
        }
    }
}
